---
- name: Configure UFW firewall
  hosts: all
  become: true

  tasks:
  #---------------------------------------------------------
  # CONFIGURE UFW FIREWALL
  #---------------------------------------------------------

    - name: Install UFW
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: true

    - name: Allow SSH
      community.general.ufw:
        rule: allow
        port: "{{ ansible_port | default(22) }}"
        proto: tcp

    - name: Set default incoming policy
      community.general.ufw:
        direction: incoming
        policy: deny

    - name: Set default outgoing policy
      community.general.ufw:
        direction: outgoing
        policy: allow

    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - name: Show UFW status
      ansible.builtin.command:
        cmd: ufw status verbose
      register: ufw_status
      changed_when: false

    - name: Display UFW status
      ansible.builtin.debug:
        var: ufw_status.stdout_lines
  